#!/bin/sh

sbcl --eval "(require 'asdf)" \
     --eval '(push #P"/home/johannes/projects/ototype/" asdf:*central-registry*)' \
     --eval '(load "~/quicklisp/setup.lisp")' \
     --eval "(asdf:make :ototype)" \
     --quit
